package pl.bartixen.bxcit.Listeners;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.event.Listener;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.InventoryHolder;
import org.bukkit.inventory.InventoryView;
import pl.bartixen.bxcit.Data.ItemBuilder;
import pl.bartixen.bxcit.Main;

public class ArmorListener implements Listener {

    static Main plugin;

    public ArmorListener(Main m) {
        plugin = m;
    }

    public static InventoryView guicowboy(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.cowboy.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.cowboy.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.cowboy.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.cowboy.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.cowboy.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Cowboy"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lCowboy z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lCowboy z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lCowboy z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lCowboy z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lCowboy z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lCowboy Hat");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lCowboy Jacket");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lCowboy Pants");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lCowboy Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguipache(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.apache.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.apache.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.apache.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.apache.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.apache.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Apache"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lApache z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lApache z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lApache z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lApache z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lApache z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lApache Hood");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lApache Cloak");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lApache Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lApache Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguiaztec(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.aztec.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.aztec.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.aztec.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.aztec.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.aztec.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Aztec"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lAztec z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lAztec z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lAztec z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lAztec z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lAztec z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lAztec Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lAztec Cloak");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lAztec Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lAztec Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguiguard(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.guard.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.guard.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.guard.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.guard.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.guard.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Guard"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lGuard z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lGuard z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lGuard z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lGuard z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lGuard z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lGuard Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lGuard Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lGuard Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lGuard Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguiemperors(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.emperors.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.emperors.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.emperors.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.emperors.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.emperors.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Emperors"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lEmperors z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lEmperors z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lEmperors z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lEmperors z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lEmperors z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lEmperors Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lEmperors Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lEmperors Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lEmperors Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguikings(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.kings.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.kings.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.kings.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.kings.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.kings.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Kings"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lKings z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lKings z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lKings z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lKings z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lKings z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lKings Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lKings Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lKings Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lKings Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguiknights(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.kinghts.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.kinghts.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.kinghts.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.kinghts.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.kinghts.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Knights"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lKnights z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lKnights z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lKnights z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lKnights z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lKnights z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lKnights Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lKnights Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lKnights Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lKnights Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguininja(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.ninja.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.ninja.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.ninja.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.ninja.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.ninja.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Ninja"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lNinja z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lNinja z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lNinja z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lNinja z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lNinja z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lNinja Mask");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lNinja Tunic");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lNinja Pants");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lNinja Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguinordic(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.nordic.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.nordic.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.nordic.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.nordic.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.nordic.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Nordic"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lNordic z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lNordic z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lNordic z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lNordic z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lNordic z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lNordic Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lNordic Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lNordic Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lNordic Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguibone(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.bone.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.bone.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.bone.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.bone.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.bone.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Bone"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lBone z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lBone z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lBone z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lBone z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lBone z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lBone Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lBone Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lBone Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lBone Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguispace(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.space.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.space.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.space.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.space.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.space.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Space"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lSpace z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lSpace z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lSpace z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSpace z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lSpace z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lSpace Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSpace Jacket");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lSpace Pants");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lSpace Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguispartan(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.spartan.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.spartan.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.spartan.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.spartan.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.spartan.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Spartan"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lSpartan z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lSpartan z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lSpartan z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSpartan z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lSpartan z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lSpartan Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSpartan Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lSpartan Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lSpartan Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguidragon(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.dragon.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.dragon.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.dragon.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.dragon.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.dragon.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Dragon"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lDragon z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lDragon z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lDragon z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lDragon z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lDragon z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lDragon Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lDragon Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lDragon Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lDragon Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguisteel(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.steel.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.steel.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.steel.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.steel.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.steel.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Steel"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lSteel z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lSteel z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lSteel z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSteel z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lSteel z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lSteel Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSteel Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lSteel Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lSteel Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguielven(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.elven.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.elven.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.elven.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.elven.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.elven.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Elven"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lElven z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lElven z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lElven z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lElven z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lElven z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lElven Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lElven Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lElven Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lElven Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguisamurai(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.samurai.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.samurai.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.samurai.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.samurai.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.samurai.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Samurai"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lSamurai z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lSamurai z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lSamurai z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSamurai z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lSamurai z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lSamurai Helmet");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSamurai Chestplate");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lSamurai Leggings");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lSamurai Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

    public static InventoryView aguisteampunk(Player p) {
        int pkt_chainmail = plugin.getConfig().getInt("skin.armor.steampunk.chainmail");
        int pkt_golden = plugin.getConfig().getInt("skin.armor.steampunk.golden");
        int pkt_iron = plugin.getConfig().getInt("skin.armor.steampunk.iron");
        int pkt_diamond = plugin.getConfig().getInt("skin.armor.steampunk.diamond");
        int pkt_netherite = plugin.getConfig().getInt("skin.armor.steampunk.netherite");
        Inventory inventory = Bukkit.createInventory((InventoryHolder)p, 45, ("§9§lKup skin Steampunk"));
        ItemBuilder slot29 = (new ItemBuilder(Material.CHAINMAIL_CHESTPLATE, 1)).setTitle("§e§lSteampunk z chainmail").addLore("§7").addLore("§fCena §9" + pkt_chainmail + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(29, slot29.build());
        ItemBuilder slot30 = (new ItemBuilder(Material.GOLDEN_CHESTPLATE, 1)).setTitle("§e§lSteampunk z złota").addLore("§7").addLore("§fCena §9" + pkt_golden + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(30, slot30.build());
        ItemBuilder slot31 = (new ItemBuilder(Material.IRON_CHESTPLATE, 1)).setTitle("§e§lSteampunk z żelaza").addLore("§7").addLore("§fCena §9" + pkt_iron + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(31, slot31.build());
        ItemBuilder slot32 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSteampunk z diamentu").addLore("§7").addLore("§fCena §9" + pkt_diamond + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(32, slot32.build());
        ItemBuilder slot33 = (new ItemBuilder(Material.NETHERITE_CHESTPLATE, 1)).setTitle("§e§lSteampunk z netheraitu").addLore("§7").addLore("§fCena §9" + pkt_netherite + " pkt.").addLore("§7").addLore("§7Jeżeli chcesz kupić to kliknij");
        inventory.setItem(33, slot33.build());
        ItemBuilder slot11 = (new ItemBuilder(Material.DIAMOND_HELMET, 1)).setTitle("§e§lSteampunk Cap");
        inventory.setItem(11, slot11.build());
        ItemBuilder slot12 = (new ItemBuilder(Material.DIAMOND_CHESTPLATE, 1)).setTitle("§e§lSteampunk Tunic");
        inventory.setItem(12, slot12.build());
        ItemBuilder slot13 = (new ItemBuilder(Material.DIAMOND_LEGGINGS, 1)).setTitle("§e§lSteampunk Pants");
        inventory.setItem(13, slot13.build());
        ItemBuilder slot14 = (new ItemBuilder(Material.DIAMOND_BOOTS, 1)).setTitle("§e§lSteampunk Boots");
        inventory.setItem(14, slot14.build());
        ItemBuilder backguard = (new ItemBuilder(Material.BLACK_STAINED_GLASS_PANE, 1)).setTitle("§7");
        inventory.setItem(0, backguard.build());
        inventory.setItem(1, backguard.build());
        inventory.setItem(2, backguard.build());
        inventory.setItem(3, backguard.build());
        inventory.setItem(4, backguard.build());
        inventory.setItem(5, backguard.build());
        inventory.setItem(6, backguard.build());
        inventory.setItem(7, backguard.build());
        inventory.setItem(8, backguard.build());
        inventory.setItem(9, backguard.build());
        inventory.setItem(10, backguard.build());
        inventory.setItem(15, backguard.build());
        inventory.setItem(16, backguard.build());
        inventory.setItem(17, backguard.build());
        inventory.setItem(18, backguard.build());
        inventory.setItem(19, backguard.build());
        inventory.setItem(20, backguard.build());
        inventory.setItem(21, backguard.build());
        inventory.setItem(22, backguard.build());
        inventory.setItem(23, backguard.build());
        inventory.setItem(24, backguard.build());
        inventory.setItem(25, backguard.build());
        inventory.setItem(26, backguard.build());
        inventory.setItem(27, backguard.build());
        inventory.setItem(28, backguard.build());
        inventory.setItem(34, backguard.build());
        inventory.setItem(35, backguard.build());
        inventory.setItem(36, backguard.build());
        inventory.setItem(37, backguard.build());
        inventory.setItem(38, backguard.build());
        inventory.setItem(39, backguard.build());
        inventory.setItem(40, backguard.build());
        inventory.setItem(41, backguard.build());
        inventory.setItem(42, backguard.build());
        inventory.setItem(43, backguard.build());
        ItemBuilder slot44 = (new ItemBuilder(Material.RED_CONCRETE, 1)).setTitle("§c§lAnuluj");
        inventory.setItem(44, slot44.build());
        return p.openInventory(inventory);
    }

}
