main: pl.bartixen.bxcit.Main
version: 3.5.2
author: Bartixen
name: BxCit
api-version: 1.17
description: Plugin na skiny w minecraft
website: https://bartixen.pl

commands:
  bxcit:
    description: Pokazuje informacje o pluginie
  cit:
    description: Pokazuje informacje o pluginie
  txt:
    description: Wyswietla jak wlaczyc na serwerze texturpacka
  skiny:
    description: Otwiera gui z skinami
  skinygracz:
    description: Wyswietla wszystkie informacje o zakupach/wplatach gracza
  sg:
    description: Wyswietla wszystkie informacje o zakupach/wplatach gracza